apiVersion: v1
kind: Secret
metadata:
  name: vault-ssl-cert
  namespace: vault-deployment
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "certs/tls.key" | b64enc }}
