apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}  # Use release namespace
spec:
  ports:
    - port: {{ .Values.service.port }}      # Reference service port from values.yaml
      targetPort: {{ .Values.service.port }} # Reference target port from values.yaml
  selector:
    app: vault  # Selector to match the Vault app
  type: {{ .Values.service.type }}           # Service type (e.g., NodePort, LoadBalancer)
