apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:

        - name: VAULT_API_ADDR
          value: "http://0.0.0.0:8200"  # Explicitly set the API address
        volumeMounts:
        - name: vault-config
          mountPath: /etc/vault.d
        - name: vault-ssl-cert
          mountPath: /vault/certs
          readOnly: true  # Ensure security
        - name: vault-data
          mountPath: /vault/data   # Mount the persistent storage
    securityContext:
      capabilities:
        add:
          - IPC_LOCK  # Add IPC_LOCK capability          
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-ssl-cert
        secret:
          secretName: vault-ssl-cert  # Reference the secret containing SSL certs
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-pvc  # Reference the PVC for persistent data storage
      imagePullSecrets:
      - name: jfrog-registry-secret
