apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # You can adjust the size based on your needs
  storageClassName: manual    #standard  # Or use a different storage class if necessary