apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault.hcl: |
    storage "file" {
      path = "/vault/data"
    }
    
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 0
      tls_cert_file = "{{ .Values.certificates.tlsCrtPath }}"
      tls_key_file  = "{{ .Values.certificates.tlsKeyPath }}"
    }
    
    ui = true


    #monitoring - Grafana, Loki, prometheus
    #Scanning - Sonarcube , PRisma , checkmarx
    #SSL/TLS certificate - openssl
