apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Ensure HTTP to HTTPS redirection
    nginx.ingress.kubernetes.io/secure-backends: "true"  # Secure communication with the backend (Vault)
spec:
  rules:
  - host: vault.local  # Replace with your actual domain if needed
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vault  # Use the correct service name (vault, not vault-service)
            port:
              number: 8200
  tls:
  - hosts:
    - vault.local  # Replace with your actual domain if needed
    secretName: vault-ssl-cert  # Reference the secret containing the SSL certificate
