replicaCount: 1

image:
  repository: trial4w4crx.jfrog.io/vault-repo/vault-server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  #type: ClusterIP
  type: NodePort    # Change to LoadBalancer if needed (for cloud environments)
  port: 8200 # The port exposed by the service
  nodePort: 30805  # This should match the one in your service.yaml


vault:
  addr: "https://vault:8200"  # Default internal Vault address
  externalAddr: "https://192.168.49.2:30805"  # Default external access

# Storage Configuration
storage:
  backend: "raft"  # Use "file" for non-HA
  path: "/vault/data"
  
# Define Vault SSL certificates
certificates:
  tlsCrtPath: "/vault/certs/tls.crt"
  tlsKeyPath: "/vault/certs/tls.key"