replicaCount: 1

image:
  repository: trial4w4crx.jfrog.io/vault-repo/vault-server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8200 # The port exposed by the service      
  type: NodePort    # Change to LoadBalancer if needed (for cloud environments)


vault:
  addr: "https://vault:8200"  # Service name used within the Kubernetes cluster

# Define Vault SSL certificates
certificates:
  tlsCrtPath: "/vault/certs/tls.crt"
  tlsKeyPath: "/vault/certs/tls.key"
