name: Deploy HashiCorp Vault to Minikube (CI/CD Pipeline)

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify Docker Access
        run: docker --version

      - name: Check Helm and Kubectl Versions
        run: |
          kubectl version --client
          helm version

  build:
    runs-on: self-hosted
    needs: validate
    env:
      JFROG_REGISTRY: "triald4lybb.jfrog.io"
      JFROG_REPO: "vault-repo"
      IMAGE_NAME: "vault-server"
      BASE_VERSION: "1.0"
      IMAGE_TAG: "${{ github.run_number }}-$(date +'%Y%m%d')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v2
        with:
          registry: ${{ env.JFROG_REGISTRY }}
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            docker-${{ runner.os }}-

      - name: Build Docker Image
        run: |
          set -e  
          echo "Building Docker image..."
          docker build -t ${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/Dockerfile .

  push:
    runs-on: self-hosted
    needs: build
    env:
      JFROG_REGISTRY: "triald4lybb.jfrog.io"
      JFROG_REPO: "vault-repo"
      IMAGE_NAME: "vault-server"
      IMAGE_TAG: "${{ github.run_number }}-$(date +'%Y%m%d')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v2
        with:
          registry: ${{ env.JFROG_REGISTRY }}
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Push Docker Image to JFrog Artifactory
        run: |
          echo "Pushing Docker image to JFrog Artifactory..."
          docker push ${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Pull and Verify Docker Image
        run: |
          echo "Pulling Docker image from Artifactory for verification..."
          docker pull ${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  vulnerability_check:
    runs-on: self-hosted
    needs: push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add Trivy or other vulnerability scanning steps here

  deploy:
    runs-on: self-hosted
    needs: vulnerability_check
    env:
      JFROG_REGISTRY: "triald4lybb.jfrog.io"
      JFROG_REPO: "vault-repo"
      IMAGE_NAME: "vault-server"
      IMAGE_TAG: "${{ github.run_number }}-$(date +'%Y%m%d')"
      K8S_NAMESPACE: "vault-deployment"
      K8S_DEPLOYMENT_NAME: "vault"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Namespace if Not Exists
        run: |
          echo "Preparing Kubernetes namespace..."
          kubectl get namespace ${{ env.K8S_NAMESPACE }} || kubectl create namespace ${{ env.K8S_NAMESPACE }}

      - name: Lint Helm Chart
        run: helm lint ./helm

      - name: Cache Helm Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.helm/cache
          key: helm-${{ runner.os }}-${{ hashFiles('**/Chart.yaml', '**/values.yaml') }}
          restore-keys: |
            helm-${{ runner.os }}-

      - name: Helm Dry Run
        run: |
          echo "Performing a dry-run for Vault Helm deployment..."
          helm upgrade --install vault ./helm \
            --namespace ${{ env.K8S_NAMESPACE }} \
            --set image.repository=${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REPO }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --set server.ha.enabled=true \
            --dry-run

      - name: Install/Upgrade Vault with Helm
        run: |
          echo "Deploying Vault using Helm..."
          helm upgrade --install vault ./helm \
            --namespace ${{ env.K8S_NAMESPACE }} \
            --set image.repository=${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REPO }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --set imagePullSecrets[0].name=jfrog-registry-secret \
            --set server.ha.enabled=true \
            --create-namespace \
            --wait --timeout 300s

      - name: Check Deployment and Pod Status
        run: |
          echo "Checking deployment and pod health..."
          kubectl get all --namespace=${{ env.K8S_NAMESPACE }}
          kubectl describe deployment/${{ env.K8S_DEPLOYMENT_NAME }} --namespace=${{ env.K8S_NAMESPACE }}
          kubectl logs -l app.kubernetes.io/name=vault --namespace=${{ env.K8S_NAMESPACE }} --tail=50

      - name: Verify Helm Chart Deployment
        run: |
          echo "Verifying Helm chart deployment..."
          helm status vault --namespace ${{ env.K8S_NAMESPACE }}

      - name: Verify Vault Accessibility
        run: |
          echo "Checking Vault availability..."
          kubectl port-forward svc/vault --namespace=${{ env.K8S_NAMESPACE }} 8200:8200 &
          FORWARD_PID=$!
          sleep 5  
          curl -k http://localhost:8200/v1/sys/health || echo "Vault is not reachable!"
          kill $FORWARD_PID

      - name: Rollback on Failure
        if: failure()
        run: |
          if helm list --namespace ${{ env.K8S_NAMESPACE }} | grep -q "vault"; then
            echo "Rolling back Vault deployment..."
            helm rollback vault --namespace ${{ env.K8S_NAMESPACE }}
          else
            echo "No existing Vault deployment to roll back."
          fi

  cleanup:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete Older Docker Images from JFrog
        run: |
          echo "Deleting older images from JFrog..."
          curl -u "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }}" \
            -X DELETE "https://${{ env.JFROG_REGISTRY }}/artifactory/api/docker/${{ env.JFROG_REPO }}/v2/${{ env.IMAGE_NAME }}/tags?olderThan=3d"