name: Deploy HashiCorp Vault to Minikube (CI/CD Pipeline)

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the GitHub Actions workflow

    env:
      JFROG_REGISTRY: "trialb9kyjn.jfrog.io"
      JFROG_REPO: "vault-repo"
      IMAGE_NAME: "vault-server"
      BASE_VERSION: "1.0"
      K8S_NAMESPACE: "vault-deployment"
      K8S_DEPLOYMENT_NAME: "vault"
      JFROG_CREDENTIALS_ID: ${{ secrets.JFROG_CREDENTIALS_ID }}
      GITHUB_CREDENTIALS_ID: ${{ secrets.GITHUB_CREDENTIALS_ID }}

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set IMAGE_TAG with timestamp
    - name: Set IMAGE_TAG
      run: echo "IMAGE_TAG=${{ github.run_number }}-$(date +'%Y%m%d')" >> $GITHUB_ENV

    # Step 3: Set up Minikube
    - name: Set up Minikube
      uses: medyagh/setup-minikube@v0.0.14
      with:
        driver: docker

    # Step 4: Set Minikube Driver
    - name: Set Minikube Driver
      run: minikube config set driver docker

    # Step 5: Verify Docker access
    - name: Verify Docker Access
      run: docker --version

    # Step 6: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 7: Log in to JFrog Artifactory
    - name: Log in to JFrog Artifactory
      run: docker login ${{ env.JFROG_REGISTRY }} -u ${{ secrets.JFROG_USERNAME }} -p ${{ secrets.JFROG_PASSWORD }}

    # Step 8: Build Docker Image
    - name: Build Docker Image
      run: |
        echo "Building Docker image..."
        set -e
        docker build -t ${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/Dockerfile .
      continue-on-error: false  # Ensure build errors stop the workflow

    # Step 9: Push Docker Image to JFrog Artifactory
    - name: Push Docker Image to JFrog Artifactory
      run: |
        echo "Pushing Docker image to JFrog Artifactory..."
        docker push ${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    # Step 10: Pull and Verify Docker Image
    - name: Pull and Verify Docker Image
      run: |
        echo "Pulling Docker image from Artifactory for verification..."
        docker pull ${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    # Step 11: Lint Helm Chart
    - name: Lint Helm Chart
      run: helm lint ./helm

    # Step 12: Install Helm
    - name: Install Helm
      run: |
        echo "Installing Helm..."
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    # Step 13: Prepare Namespace in Minikube
    - name: Create Namespace if Not Exists
      run: |
        echo "Preparing Kubernetes namespace..."
        kubectl get namespace ${{ env.K8S_NAMESPACE }} || kubectl create namespace ${{ env.K8S_NAMESPACE }}

    # Step 14: Set up Minikube Image Registry (Load Docker Image into Minikube)
    - name: Load Image into Minikube
      run: |
        echo "Loading Docker image into Minikube..."
        minikube image load ${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    # Step 15: Dry Run Helm Deployment
    - name: Helm Dry Run
      run: |
        echo "Performing a dry-run for Vault Helm deployment..."
        helm upgrade --install vault ./helm \
          --namespace ${{ env.K8S_NAMESPACE }} \
          --set image.repository=${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REPO }}/${{ env.IMAGE_NAME }} \
          --set image.tag=${{ env.IMAGE_TAG }} \
          --set server.ha.enabled=true \
          --dry-run

    # Step 16: Install/Upgrade Vault using Helm in Minikube
    - name: Install/Upgrade Vault with Helm
      run: |
        echo "Deploying Vault using Helm..."
        helm upgrade --install vault ./helm \
          --namespace ${{ env.K8S_NAMESPACE }} \
          --set image.repository=${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REPO }}/${{ env.IMAGE_NAME }} \
          --set image.tag=${{ env.IMAGE_TAG }} \
          --set server.ha.enabled=true \
          --create-namespace

    # Step 17: Verify Deployment & Check Pod Status
    - name: Check Deployment and Pod Status
      run: |
        echo "Checking deployment and pod health..."
        kubectl get all --namespace=${{ env.K8S_NAMESPACE }}
        kubectl describe deployment/${{ env.K8S_DEPLOYMENT_NAME }} --namespace=${{ env.K8S_NAMESPACE }}
        kubectl logs -l app.kubernetes.io/name=vault --namespace=${{ env.K8S_NAMESPACE }} --tail=50

    # Step 18: Verify Helm Chart Deployment
    - name: Verify Helm Chart Deployment
      run: |
        echo "Verifying Helm chart deployment..."
        helm status vault --namespace ${{ env.K8S_NAMESPACE }}

    # Step 19: Rollback on Failure
    - name: Rollback on Failure
      if: failure()
      run: helm rollback vault --namespace ${{ env.K8S_NAMESPACE }}
